### ISSUE TITLE
Open a specific computer based on URL

### ISSUE THREAD

**Issue by exerro** [SquidDev-CC/copy-cat#16]
This is a bit of a wacky idea and somewhat inspired by [this CC:T issue](https://github.com/SquidDev-CC/CC-Tweaked/issues/133).

I think
* Maintaining documentation on the web as well as inside CC is a pain. It would be better to have the CC version as a canonical source of documentation with the web acting as a mirror to that.
* Having a one-click demo/tutorial link for any program would be super awesome.

So what if you could go to the cloud catcher URL with `?computer_data=<url>`, and it would use that given URL as a source for the filesystem of the emulated computer.

Some issues I'm aware of:
* Some fs functions, notably `fs.list`, wouldn't really work here.
  * Have `.cloud-catcher-files` at root, use this to download files locally, ..., profit?
  * Limit to GitHub URLs and use the GitHub API to enumerate files?
* I'm not sure how cloud-catcher stores files locally, but these would ideally be temporary computer instances that are thrown away after use (can warn on startup). This could be awkward to implement.
  * Temporary computer directories named with some time-dependent hash that are removed automatically every now and then?

Now, this isn't a complete solution for documentation. You don't want to load a web page, spin up a Lua VM, and start an emulator, just to see how to use a particular function. This is more for looking at the docs of a system, potentially interactively if the system lets you. I think it would open up a possibility and give an incentive to developers to give their programs really good in-game docs, which is beneficial for everyone.

Intended use:
> For documentation, \[run `myproject help`](cloud-catcher-url?computer_data=https://myproject.what/.../computer)
> Alternatively, see [the wiki](wiki) for a reference to all functions.
> ...
> \<screenshots>
> \[You can also run these live](cloud-catcher-url?computer_data=https://myproject.what/.../demos)

This is very much a "feedback wanted"/"suggestion" issue... I don't know if it's feasible or even particularly useful. I just had "I wish I could do this" moment. I guess the biggest counter to this is "emulators and `pastebin run ...`", which I'll be honest is a pretty good alternative, just not quite as slick, easy, or accessible in my opinion.

**Comment by viluon** [comment]
You could just download a zip archive and unpack it before starting the emulator. See [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ) for some relevant resources.

**Comment by SquidDev** [comment]
This is already possible, albeit in a confusing and undocumented way (well, it's mentioned on the forum post, but that's it).

CC accepts a base64-encoded `startup` parameter (i.e. `?startup=base64_string`), which overwrites the startup file. For instance, [this link][mbs] will install mbs.

We also support a temporary file system for GitHub branch/PR versions. For example, see [the "master" build][mbs_master]. I guess it might be worth exposing this to the "main" version too, via a query parameter.

Ideally cc would be embeddable in other websites, so you could have a little pop-up computer to run demos instead of linking to another website. That's the plan for tweaked.cc at least, I "just" need to look into a nice way of doing it all :).

---

> Maintaining documentation on the web as well as inside CC is a pain. It would be better to have the CC version as a canonical source of documentation with the web acting as a mirror to that.

I think this is orthogonal to the original issue, but just a little confused by what you're saying here.

[mbs]: https://copy-cat.squiddev.cc/?startup=ZnMuZGVsZXRlKCJtYnMubHVhIikKaWYgc2hlbGwucnVuKCJ3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9TcXVpZERldi1DQy9tYnMvbWFzdGVyL21icy5sdWEgbWJzLmx1YSIpIGFuZCBzaGVsbC5ydW4oIm1icyBpbnN0YWxsIikgdGhlbiBvcy5yZWJvb3QoKSBlbmQ=
[mbs_master]: https://copy-cat.squiddev.cc/gh/branch/master?startup=ZnMuZGVsZXRlKCJtYnMubHVhIikKaWYgc2hlbGwucnVuKCJ3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9TcXVpZERldi1DQy9tYnMvbWFzdGVyL21icy5sdWEgbWJzLmx1YSIpIGFuZCBzaGVsbC5ydW4oIm1icyBpbnN0YWxsIikgdGhlbiBvcy5yZWJvb3QoKSBlbmQ=

**Comment by exerro** [comment]
Oh, nice! How does the temporary filesystem work? Is it always temporary, or is that specified somehow?

Having an emulator embeddable would be amazing but I can see how that'd be difficult. Is there anything stopping an iframe pointing to a copy-cat URL?

---

> Maintaining documentation on the web as well as inside CC is a pain. It would be better to have the CC version as a canonical source of documentation with the web acting as a mirror to that.

A part my reasoning for wanting this was that you could point users to a copy-cat URL for in-game docs while they're on the web. It wasn't directly related to the issue, but is something that ~~would be~~ is helped by being able to give startup scripts.

**Comment by SquidDev** [comment]
> How does the temporary filesystem work? Is it always temporary, or is that specified somehow?

It's always temporary. We just ignore any reads/writes to local storage, which means nothing is persisted:

https://github.com/SquidDev-CC/copy-cat/blob/70030566817f9ce12f846e64e89fd087c0ea3a0b/src/web/ts/computer/index.tsx#L90

> Having an emulator embeddable would be amazing but I can see how that'd be difficult. Is there anything stopping an iframe pointing to a copy-cat URL?

Mostly because you've got all the additional UI (editor, sidebar, etc..). You really need a version without any of that. Also iframes are kinda ugly - ideally it'd just be an npm package or something...

**Comment by SquidDev** [comment]
I don't think there's anything else which needs to be done here. Shout if there is.
